name:                ps-cst-dumper
version:             0.1.0.0
github:              "jvliwanag/ps-cst-dumper"
license:             BSD3
author:              "Jan Vincent Liwanag"
maintainer:          "jvliwanag@gmail.com"
copyright:           "Jan Vincent Liwanag"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jvliwanag/ps-cst-dumper#readme>

dependencies:
- base >= 4.7 && < 5
- open-browser
- pretty-show
- purescript
- text

library:
  source-dirs: src

executables:
  ps-cst-dumper:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ps-cst-dumper

tests:
  ps-cst-dumper-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ps-cst-dumper
